<a href="https://colab.research.google.com/github/NecipOz/dwpython/blob/main/Assignment_1_Student_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

___

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" alt="Rossum"></p>

In this assignment you will start off with Numpy Exercises and then complete the whole Exercise with Pandas questions. All the subjects related to questions here already covered in preclass materials and in-class sessions. So good luck!


#### 1. Import NumPy Library

In [ ]:
import numpy as np

#### 2. Create an array from my_list=[5,10,15,20,25]

In [ ]:
my_list=[5,10,15,20,25]
my_array = np.array(my_list)
my_array

array([ 5, 10, 15, 20, 25])

#### 3. Generate an array 5x5 zeros 

In [ ]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

#### 4. Generate an array 4x4 ones assign data type int

In [ ]:
n1 = np.ones((4,4), dtype=int)
n1


array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

#### 5. Make all the values of the array above 7

In [ ]:

n1*7

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

#### 6. Create same array above with full method

In [ ]:
np.full((4,4),7,dtype=int)

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

#### 7. Create an array of even integers from 2 to 16 

In [ ]:
np.arange(2,17,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16])

#### 8. Create a 5x5 matrix with values between 0 to 25

In [ ]:
np.arange(25).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### 9. Create a 5x5 matrix with values between 0 to 25 using linspace

In [ ]:
np.linspace(0,24,25, dtype=int).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### 10. Create 5 random number with numpy

In [ ]:
np.random.rand(5)

array([0.41274122, 0.51955599, 0.95543619, 0.67521641, 0.22029637])

#### 11. Create random normal distributed 5x5 array

In [ ]:
np.random.randn(5,5)

array([[ 3.36967432e-01, -1.08731767e+00, -1.37088962e+00,
         3.10210812e-01,  2.92562744e-01],
       [ 1.08224023e+00,  4.60928843e-02,  1.34054893e+00,
        -1.08472244e+00, -7.98361027e-01],
       [ 1.31156207e-03,  2.37340675e-01,  7.29571303e-01,
        -6.77599519e-02,  1.87690922e+00],
       [ 6.14038103e-01, -9.28457492e-01, -9.22119340e-01,
         2.04240356e+00,  1.37852913e+00],
       [ 9.72679392e-01, -1.60082988e+00,  4.96518505e-01,
         1.63593674e+00,  1.67687157e+00]])

#### 12. Create 3x4 shaped array with random int numbers between 20 and 50 with numpy

In [ ]:
np.random.randint(20,50, size = (3,4))

array([[31, 45, 27, 39],
       [23, 25, 44, 38],
       [45, 28, 23, 34]])

#### 13. Reshape the array below with shape 6x8

In [ ]:
arr = np.arange(36)
ranarr = np.random.randint(0, 52, 48)

In [ ]:
ranarr

array([ 6, 20, 51, 26, 16, 13, 17, 14, 15, 34, 41,  3, 49, 25, 36, 13, 34,
       46, 21,  5, 20, 14, 29, 21, 35, 28, 45, 35,  5, 20, 32, 50, 31,  6,
       50, 45,  4, 22, 49, 15, 37, 50, 24, 42, 27,  8, 26, 47])

In [ ]:
ranarr = ranarr.reshape(6,8)
ranarr

array([[ 6, 20, 51, 26, 16, 13, 17, 14],
       [15, 34, 41,  3, 49, 25, 36, 13],
       [34, 46, 21,  5, 20, 14, 29, 21],
       [35, 28, 45, 35,  5, 20, 32, 50],
       [31,  6, 50, 45,  4, 22, 49, 15],
       [37, 50, 24, 42, 27,  8, 26, 47]])

In [ ]:
#reshape with -1
ranarr.reshape(4,12)    


array([[ 6, 20, 51, 26, 16, 13, 17, 14, 15, 34, 41,  3],
       [49, 25, 36, 13, 34, 46, 21,  5, 20, 14, 29, 21],
       [35, 28, 45, 35,  5, 20, 32, 50, 31,  6, 50, 45],
       [ 4, 22, 49, 15, 37, 50, 24, 42, 27,  8, 26, 47]])

In [ ]:
ranarr.reshape(-1,12)

array([[ 6, 20, 51, 26, 16, 13, 17, 14, 15, 34, 41,  3],
       [49, 25, 36, 13, 34, 46, 21,  5, 20, 14, 29, 21],
       [35, 28, 45, 35,  5, 20, 32, 50, 31,  6, 50, 45],
       [ 4, 22, 49, 15, 37, 50, 24, 42, 27,  8, 26, 47]])

## Numpy Indexing and Selection


In [ ]:
#Create array below
mat= np.arange(1,17).reshape(4,4)
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

#### 14. Write code that reproduces the output shown below.<br>

In [ ]:
mat[1:3,1:3]

array([[ 6,  7],
       [10, 11]])

#### 15. Get the first column of the array.

In [ ]:
mat[:,0]

array([ 1,  5,  9, 13])

#### 16. Get the values in 2nd row for every 2 step.

In [ ]:
mat[1,(0,2)]

array([5, 7])

#### 17.Assign 77 to every cell in 3rd column.

In [ ]:
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [ ]:
mat[:,2] = 77
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

#### 18. Take 2nd row 1st column, 4th row 2nd column.

In [ ]:
mat[[1,3],[0,1]]

array([ 5, 14])

#### 19. Take between 2nd and last row with step 2 and between 1 and last column with step 2.

In [ ]:
mat[[1,3],0:3:2]

array([[ 5, 77],
       [13, 77]])

## NumPy Operations

#### 20. Get the sum of values smaller than 10 and values bigger than 12 from array above 

In [ ]:
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [ ]:
mat[mat<10]

array([1, 2, 4, 5, 6, 8, 9])

In [ ]:
mat[mat>12]

array([77, 77, 77, 13, 14, 77, 16])

In [ ]:
mat[mat<10] + mat[mat>12]

array([78, 79, 81, 18, 20, 85, 25])

#### 21. Get the standard deviation of the result above

In [ ]:
(mat[mat<10] + mat[mat>12]).std()

29.700546274093877

#### 22. Get the sum of second column from array above

In [ ]:
#print array here
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [ ]:
sum(mat[:,1])

32

#### 23. Get the median,mean and std of 3rd row from array above

In [ ]:
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
mat[2]

array([ 9, 10, 11, 12])

In [ ]:
#median
np.median(mat[2])

10.5

In [ ]:
#mean
mat[2].mean()

10.5

In [ ]:
#std
mat[2].std()

1.118033988749895

# Pandas Section

In [ ]:
import pandas as pd


**Read Salaries.csv take a look at first 5 rows, df info and df statistical measurements**

In [ ]:
sal=pd.read_csv('Salaries.csv')


In [ ]:
sal.head()

Id       EmployeeName  ...         Agency  Status
0   1     NATHANIEL FORD  ...  San Francisco     NaN
1   2       GARY JIMENEZ  ...  San Francisco     NaN
2   3     ALBERT PARDINI  ...  San Francisco     NaN
3   4  CHRISTOPHER CHONG  ...  San Francisco     NaN
4   5    PATRICK GARDNER  ...  San Francisco     NaN

[5 rows x 13 columns]

In [ ]:
sal.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype  
---  ------            --------------   -----  
 0   Id                148654 non-null  int64  
 1   EmployeeName      148654 non-null  object 
 2   JobTitle          148654 non-null  object 
 3   BasePay           148045 non-null  float64
 4   OvertimePay       148650 non-null  float64
 5   OtherPay          148650 non-null  float64
 6   Benefits          112491 non-null  float64
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64  
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object 
 12  Status            0 non-null       float64
dtypes: float64(8), int64(2), object(3)
memory usage: 14.7+ MB


In [ ]:
sal.describe()

Id        BasePay  ...  Notes  Status
count  148654.000000  148045.000000  ...    0.0     0.0
mean    74327.500000   66325.448841  ...    NaN     NaN
std     42912.857795   42764.635495  ...    NaN     NaN
min         1.000000    -166.010000  ...    NaN     NaN
25%     37164.250000   33588.200000  ...    NaN     NaN
50%     74327.500000   65007.450000  ...    NaN     NaN
75%    111490.750000   94691.050000  ...    NaN     NaN
max    148654.000000  319275.010000  ...    NaN     NaN

[8 rows x 10 columns]

**How many different year value are there**

In [ ]:
sal[["Year"]].value_counts()

Year
2014    38123
2013    37606
2012    36766
2011    36159
dtype: int64

**Print out max and avg Totalpay**

In [ ]:
#max
sal['TotalPay'].max()

567595.43

In [ ]:
#avg
sal['TotalPay'].mean()

74768.321971703

**How many records are there which have TotalPay bigger than avg TotalPay**

In [ ]:
sal[sal['TotalPay'] > sal['TotalPay'].mean()]["TotalPay"].nunique()

64489

**How much does ALBERT PARDINI make (including benefits)?**

In [ ]:
sal[sal['EmployeeName'] =="ALBERT PARDINI"]["TotalPayBenefits"]

2    335279.91
Name: TotalPayBenefits, dtype: float64

**Who is lowest paid person**

In [ ]:
sal[sal['TotalPay'] == sal['TotalPay'].min()]["EmployeeName"]

148653    Joe Lopez
Name: EmployeeName, dtype: object

**What are the unique Jobs in dataset?**

In [ ]:
sal.JobTitle.unique()

array(['GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY',
       'CAPTAIN III (POLICE DEPARTMENT)',
       'WIRE ROPE CABLE MAINTENANCE MECHANIC', ..., 'Conversion',
       'Cashier 3', 'Not provided'], dtype=object)

**List 3 least common Jobs**

In [95]:
sal.JobTitle.value_counts().tail(3)

HH Mechanical Shop Sprv              1
ASSOCIATE HUMAN RESOURCES ANALYST    1
COURT ASSISTANT, SUPERIOR COURT      1
Name: JobTitle, dtype: int64

**How many people earned more than avg in 2012**

In [106]:
sal[(sal.Year == 2012) & (sal.TotalPayBenefits>sal.TotalPayBenefits.mean())]["Id"].count()

20366

**How many people have the word Manager in their job title?**

In [219]:
#use apply function here
def manager_control(x):
  if 'manager' in x.lower():
    return True
  else:
    return False

len(sal[sal.JobTitle.apply(manager_control)== True])



4110

**Take Id,EmployeeName,JobTitle,TotalPay and TotalPayBenefits columns with iloc and assign it as sal_new dataframe**

In [ ]:
sal.head()

Id       EmployeeName                                        JobTitle  \
0   1     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

     BasePay  OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.00  400184.25       NaN  567595.43         567595.43   
1  155966.02    245131.88  137811.38       NaN  538909.28         538909.28   
2  212739.13    106088.18   16452.60       NaN  335279.91         335279.91   
3   77916.00     56120.71  198306.90       NaN  332343.61         332343.61   
4  134401.60      9737.00  182234.59       NaN  326373.19         326373.19   

   Year  Notes         Agency  Status  
0  2011    NaN  San Francisco     NaN  
1  2011    NaN  San Francisco     NaN  
2  2011    NaN  San Francisco     NaN  
3  2011    NaN  San Francisco     NaN  
4  2011    NaN  San Francisco     NaN

In [159]:
sal_new = sal.iloc[:,[0,1,2,7,8]]
sal_new

Id       EmployeeName  ...   TotalPay  TotalPayBenefits
0            1     NATHANIEL FORD  ...  567595.43         567595.43
1            2       GARY JIMENEZ  ...  538909.28         538909.28
2            3     ALBERT PARDINI  ...  335279.91         335279.91
3            4  CHRISTOPHER CHONG  ...  332343.61         332343.61
4            5    PATRICK GARDNER  ...  326373.19         326373.19
...        ...                ...  ...        ...               ...
148649  148650      Roy I Tillery  ...       0.00              0.00
148650  148651       Not provided  ...       0.00              0.00
148651  148652       Not provided  ...       0.00              0.00
148652  148653       Not provided  ...       0.00              0.00
148653  148654          Joe Lopez  ...    -618.13           -618.13

[148654 rows x 5 columns]

**Take columns betweeen EmployeeName and TotalPayBenefits with loc and assign it o sal_new df**
 

In [231]:
sal_new = sal_new.loc["EmployeeName":"TotalPayBenefits"]
sal_new

Series([], Name: EmployeeName, dtype: object)

**Print out the names of the employees who earn more than min, but less than avg**

In [162]:
sal[(sal.TotalPayBenefits > sal.TotalPayBenefits.min()) & (sal.TotalPayBenefits < sal.TotalPayBenefits.mean())]["EmployeeName"]

10806            KWE LEE
10807     MIGUEL CARO JR
10808      JOANNE MORRIS
10809      LAYLA WELBORN
10810            LE BANH
               ...      
148648       Leon Walker
148649     Roy I Tillery
148650      Not provided
148651      Not provided
148652      Not provided
Name: EmployeeName, Length: 75649, dtype: object